### PR TITLE
Few bug fixes, and extra functionality

### PR DESCRIPTION
**Pull request by rjrudman**
This pull request fixes:
-  .gitignore using the standard visual studio file: https://github.com/github/gitignore/blob/master/VisualStudio.gitignore
- Fixed compile error in IDelugeClient
- Added Paused and Downloaded states for torrents.
- Fixed Hash not being stored in the Torrent object
- Added functionality to upload magnet links
- Added functionality to change torrent trackers

### CODE REVIEW

**Comment by ScottBurfieldMills** [comment]
It would be good to have this merged in!

I ran into the same issues and ended up implementing the fixes covered in https://github.com/bojanrajkovic/libdelugeclient-sharp/pull/1/commits/4d115ee3bb57bced3b80c2b998d764b976321c9b, https://github.com/bojanrajkovic/libdelugeclient-sharp/pull/1/commits/9adb6a5e76e61ec0f60b0cec77edea1a8eb87693 and https://github.com/bojanrajkovic/libdelugeclient-sharp/pull/1/commits/77bfb5304eebcbe6a656cabcfa4d9675d8cef65a before I realised there was an existing pull request that fixed these.

**Comment by bojanrajkovic** [comment]
Wow, I didn't even notice this PR. :) Thanks for the contribution! 

Will merge this, though I'm probably going to start implementing an actual Deluge RPC client soon rather than relying on the Web UI's JSON-RPC endpoint, which always felt hacky. When I started this, I was green and befuddled by the actual core RPC protocol that the thin client uses, but I think I understand it a lot better now.

**Comment by ScottBurfieldMills** [comment]
There are some other fixes that I've made (a missing State from the State.cs file, handling some type casting errors). Is it worth sending a pull request?

**Comment by bojanrajkovic** [comment]
Yeah, certainly for now. It’s gonna be a little while before I get going on a proper RPC lib.

________________________________

**Pull request merged**
